#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# Media Labs Automobile — Oracle Cloud VM Provisioning Script
# ═══════════════════════════════════════════════════════════════
# Usage: ssh into Oracle VM → bash provision-oracle.sh
#
# What this script does:
#   1. Installs Docker + Docker Compose
#   2. Installs Nginx + Certbot
#   3. Clones the repo
#   4. Builds and starts RADAR + STUDIO containers
#   5. Copies Nginx config
#   6. Sets up SSL (after DNS is configured)
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

DOMAIN="media-labs.is-a.dev"
REPO_URL="https://github.com/nouredine-diallo/media_autombile.git"
INSTALL_DIR="/opt/media-labs"

echo "═══════════════════════════════════════════════════"
echo "  Media Labs Automobile — VM Provisioning"
echo "═══════════════════════════════════════════════════"
echo ""

# ── 1. System update ──
echo "[1/8] Updating system..."
sudo apt-get update -qq
sudo apt-get upgrade -y -qq

# ── 2. Install Docker ──
echo "[2/8] Installing Docker..."
if ! command -v docker &>/dev/null; then
    curl -fsSL https://get.docker.com | sudo sh
    sudo usermod -aG docker ubuntu
    echo "  Docker installed: $(docker --version)"
else
    echo "  Docker already installed: $(docker --version)"
fi

# ── 3. Install Docker Compose plugin ──
echo "[3/8] Installing Docker Compose plugin..."
if ! docker compose version &>/dev/null; then
    sudo apt-get install -y docker-compose-plugin
fi
echo "  Compose: $(docker compose version)"

# ── 4. Install Nginx ──
echo "[4/8] Installing Nginx..."
if ! command -v nginx &>/dev/null; then
    sudo apt-get install -y nginx
    sudo systemctl enable nginx
    sudo systemctl start nginx
fi
echo "  Nginx: $(nginx -v 2>&1)"

# ── 5. Install Certbot ──
echo "[5/8] Installing Certbot..."
if ! command -v certbot &>/dev/null; then
    sudo apt-get install -y certbot python3-certbot-nginx
fi

# ── 6. Clone repo ──
echo "[6/8] Cloning repository..."
if [ -d "$INSTALL_DIR" ]; then
    echo "  Directory exists, pulling latest..."
    cd "$INSTALL_DIR"
    git pull
else
    sudo git clone "$REPO_URL" "$INSTALL_DIR"
    sudo chown -R ubuntu:ubuntu "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi

# ── 7. Create .env file ──
echo "[7/8] Creating .env file..."
if [ ! -f "$INSTALL_DIR/.env" ]; then
    SESSION_SECRET=$(openssl rand -base64 32)
    cat > "$INSTALL_DIR/.env" <<EOF
# Media Labs Automobile — Production Environment
# Generated by provision-oracle.sh on $(date)

# Shared
SESSION_SECRET=$SESSION_SECRET
GROQ_API_KEY=${GROQ_API_KEY:-gsk_your_key_here}
AUTH_PASSWORD=work

# Google (optional)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=https://radar.media-labs.is-a.dev/api/auth/google/callback
EOF
    echo "  ⚠️  Edit $INSTALL_DIR/.env to set GROQ_API_KEY!"
else
    echo "  .env already exists, skipping."
fi

# ── 8. Build and start containers ──
echo "[8/8] Building and starting Docker containers..."
cd "$INSTALL_DIR"
docker compose build --no-cache
docker compose up -d

echo ""
echo "═══════════════════════════════════════════════════"
echo "  ✅ Containers started!"
echo "═══════════════════════════════════════════════════"
echo ""
echo "  RADAR:   http://localhost:3001"
echo "  STUDIO:  http://localhost:3002"
echo ""
echo "  ── Next steps ──"
echo "  1. Set DNS records for $DOMAIN → $(curl -s ifconfig.me)"
echo "  2. Run: sudo certbot --nginx -d $DOMAIN -d radar.$DOMAIN -d studio.$DOMAIN"
echo "  3. Copy Nginx config: sudo cp nginx/media-labs.conf /etc/nginx/sites-available/"
echo "  4. Enable: sudo ln -sf /etc/nginx/sites-available/media-labs.conf /etc/nginx/sites-enabled/"
echo "  5. Test: sudo nginx -t && sudo systemctl reload nginx"
echo ""
echo "  Or run the SSL setup script:"
echo "  bash setup-ssl.sh"
echo ""

# ── 9. Copy landing page ──
sudo mkdir -p /opt/media-labs/landing
sudo cp "$INSTALL_DIR/landing/index.html" /opt/media-labs/landing/
sudo cp -r "$INSTALL_DIR/nginx" /opt/media-labs/

echo "  Done! 🚀"
