#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# Media Labs Automobile — Oracle Cloud VM Provisioning Script
# ═══════════════════════════════════════════════════════════════
# Usage : ssh into Oracle VM → bash provision-oracle.sh
# Idempotent : peut être relancé sans casser l'existant.
#
# Ce que fait ce script :
#   1. Installe Docker + Docker Compose
#   2. Installe Nginx + Certbot
#   3. Ouvre les ports 80/443 dans iptables (piège classique Oracle)
#   4. Clone le repo dans /opt/media-labs
#   5. Crée le .env (secrets générés)
#   6. Installe une conf Nginx HTTP (bootstrap, proxy vers les apps)
#   7. Build et démarre les conteneurs RADAR + STUDIO
#   8. SI le DNS pointe déjà ici : certs Let's Encrypt + conf SSL finale.
#      SINON : message clair → relancer setup-ssl.sh après la PR DNS.
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

DOMAIN="media-labs.is-a.dev"
REPO_URL="https://github.com/nouredine-diallo/media_autombile.git"
INSTALL_DIR="/opt/media-labs"

echo "═══════════════════════════════════════════════════"
echo "  Media Labs Automobile — VM Provisioning"
echo "═══════════════════════════════════════════════════"
echo ""

# ── 1. Update système ──
echo "[1/8] Updating system..."
sudo apt-get update -qq

# ── 2. Docker ──
echo "[2/8] Installing Docker..."
if ! command -v docker &>/dev/null; then
    curl -fsSL https://get.docker.com | sudo sh
    sudo usermod -aG docker ubuntu
fi
sudo systemctl enable --now docker >/dev/null 2>&1 || true
echo "  Docker: $(sudo docker --version)"

# ── 3. Docker Compose plugin ──
echo "[3/8] Checking Docker Compose..."
if ! sudo docker compose version &>/dev/null; then
    sudo apt-get install -y docker-compose-plugin
fi
echo "  Compose: $(sudo docker compose version)"

# ── 4. Nginx + Certbot + iptables ──
echo "[4/8] Installing Nginx + Certbot..."
sudo apt-get install -y nginx certbot python3-certbot-nginx >/dev/null
sudo systemctl enable --now nginx >/dev/null 2>&1 || true

# Piège Oracle : l'image Ubuntu a des règles iptables restrictives.
for port in 80 443; do
    sudo iptables -C INPUT -p tcp --dport "$port" -j ACCEPT 2>/dev/null || \
        sudo iptables -I INPUT 1 -p tcp --dport "$port" -j ACCEPT
done
if command -v netfilter-persistent &>/dev/null; then
    sudo netfilter-persistent save >/dev/null
fi
echo "  Ports 80/443 ouverts ($(nginx -v 2>&1), $(certbot --version 2>&1 | head -1))"

# ── 5. Clone repo ──
echo "[5/8] Cloning repository..."
if [ -d "$INSTALL_DIR/.git" ]; then
    cd "$INSTALL_DIR"
    git pull --ff-only
else
    rm -rf "$INSTALL_DIR"
    sudo git clone "$REPO_URL" "$INSTALL_DIR"
    sudo chown -R ubuntu:ubuntu "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi
echo "  $(git log --oneline -1)"

# ── 6. .env ──
echo "[6/8] Creating .env file..."
if [ ! -f "$INSTALL_DIR/.env" ]; then
    SESSION_SECRET=$(openssl rand -base64 32)
    IMPORT_SECRET=$(openssl rand -hex 32)
    cat > "$INSTALL_DIR/.env" <<EOF
# Media Labs Automobile — Production Environment
# Generated by provision-oracle.sh on $(date)

SESSION_SECRET=$SESSION_SECRET
IMPORT_SECRET=$IMPORT_SECRET
GROQ_API_KEY=gsk_your_key_here
AUTH_PASSWORD=work

GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=https://radar.$DOMAIN/api/auth/google/callback
EOF
    chmod 600 "$INSTALL_DIR/.env"
    echo "  ⚠️  Édite $INSTALL_DIR/.env pour mettre la vraie GROQ_API_KEY !"
else
    echo "  .env existe déjà, conservé."
fi

# ── 7. Conf Nginx bootstrap (HTTP seul, sans certificats) ──
echo "[7/8] Installing bootstrap Nginx config (HTTP)..."
sudo mkdir -p /var/www/certbot
cat > /tmp/media-labs-bootstrap.conf <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN *.$DOMAIN;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        client_max_body_size 50m;
    }
}
EOF
sudo cp /tmp/media-labs-bootstrap.conf /etc/nginx/sites-available/media-labs.conf
sudo ln -sf /etc/nginx/sites-available/media-labs.conf /etc/nginx/sites-enabled/media-labs.conf
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t && sudo systemctl reload nginx
echo "  ✅ Nginx HTTP actif (proxy → RADAR:3001)"

# ── 8. Build + start containers ──
echo "[8/8] Building and starting Docker containers..."
echo "     (10-25 min sur ARM : Chromium Playwright + modèle embeddings ~500 Mo)"
cd "$INSTALL_DIR"
sudo docker compose build
sudo docker compose up -d

# Attente santé des deux apps
for app in 3001 3002; do
    ok=0
    for i in $(seq 1 30); do
        if curl -sf -o /dev/null "http://127.0.0.1:$app"; then ok=1; break; fi
        sleep 5
    done
    if [ "$ok" = "1" ]; then echo "  ✅ App sur :$app répond"; else echo "  ❌ App sur :$app ne répond pas (voir 'sudo docker compose logs')"; fi
done

# ── 9. SSL si le DNS est déjà en place ──
VM_IP=$(curl -s --max-time 10 ifconfig.me || echo "")
DNS_IP=$(dig +short "$DOMAIN" @8.8.8.8 2>/dev/null | head -1 || echo "")
echo ""
if [ -n "$DNS_IP" ] && [ "$DNS_IP" = "$VM_IP" ]; then
    echo "[SSL] DNS OK ($DOMAIN → $VM_IP), obtention des certificats..."
    sudo mkdir -p /var/www/certbot
    sudo certbot certonly --webroot -w /var/www/certbot \
        -d "$DOMAIN" -d "radar.$DOMAIN" -d "studio.$DOMAIN" \
        --non-interactive --agree-tos --email "admin@$DOMAIN" --keep-until-expiring
    sudo cp "$INSTALL_DIR/nginx/media-labs.conf" /etc/nginx/sites-available/media-labs.conf
    sudo nginx -t && sudo systemctl reload nginx
    echo ""
    echo "═══════════════════════════════════════════════════"
    echo "  ✅ Déploiement complet !"
    echo "═══════════════════════════════════════════════════"
    echo "  🌐 https://$DOMAIN          → Dashboard RADAR"
    echo "  🌐 https://radar.$DOMAIN    → RADAR"
    echo "  🌐 https://studio.$DOMAIN   → STUDIO"
else
    echo "═══════════════════════════════════════════════════"
    echo "  ✅ Conteneurs démarrés (RADAR :3001, STUDIO :3002)"
    echo "═══════════════════════════════════════════════════"
    echo ""
    echo "  ⏳ SSL en attente du DNS :"
    echo "     $DOMAIN doit pointer (A) vers $VM_IP"
    echo "     radar/studio.$DOMAIN en CNAME vers $DOMAIN"
    echo "     (JSON prêts dans $INSTALL_DIR/is-a-dev/ — PR sur github.com/is-a-dev/register)"
    echo ""
    echo "  Une fois la PR fusionnée et le DNS propagé (~qq min à qq h), lance :"
    echo "     bash $INSTALL_DIR/setup-ssl.sh"
fi

echo ""
echo "  Rappel : renseigne GROQ_API_KEY dans $INSTALL_DIR/.env puis :"
echo "     cd $INSTALL_DIR && sudo docker compose up -d"
